export const CEFR_WORDS: Record<string, 'A1' | 'A2' | 'B1' | 'B2' | 'C1' | 'C2'> = {
  // A1 words
  go: 'A1', eat: 'A1', house: 'A1', big: 'A1', love: 'A1', time: 'A1', day: 'A1',
  good: 'A1', work: 'A1', people: 'A1', see: 'A1', come: 'A1', get: 'A1', make: 'A1',
  know: 'A1', take: 'A1', think: 'A1', look: 'A1', want: 'A1', give: 'A1', use: 'A1',
  find: 'A1', tell: 'A1', ask: 'A1', seem: 'A1', feel: 'A1', try: 'A1', leave: 'A1',
  call: 'A1', keep: 'A1', let: 'A1', begin: 'A1', show: 'A1', hear: 'A1', play: 'A1',
  run: 'A1', move: 'A1', live: 'A1', hold: 'A1', bring: 'A1', happen: 'A1', write: 'A1',
  sit: 'A1', stand: 'A1', lose: 'A1', pay: 'A1', meet: 'A1', include: 'A1', learn: 'A1',
  change: 'A1', stop: 'A1', create: 'A1', speak: 'A1', read: 'A1', spend: 'A1',
  grow: 'A1', open: 'A1', walk: 'A1', win: 'A1', remember: 'A1', buy: 'A1', wait: 'A1',
  send: 'A1', build: 'A1', stay: 'A1', fall: 'A1', cut: 'A1', reach: 'A1', kill: 'A1',
  remain: 'A1', raise: 'A1', pass: 'A1', sell: 'A1', decide: 'A1', pull: 'A1',
  dog: 'A1', cat: 'A1', car: 'A1', food: 'A1', water: 'A1', home: 'A1',
  name: 'A1', year: 'A1', man: 'A1', woman: 'A1', child: 'A1', school: 'A1', city: 'A1',
  book: 'A1', room: 'A1', door: 'A1', hand: 'A1', head: 'A1', eye: 'A1', face: 'A1',
  place: 'A1', thing: 'A1', way: 'A1', life: 'A1', night: 'A1', old: 'A1', new: 'A1',
  little: 'A1', right: 'A1', left: 'A1', high: 'A1', long: 'A1', small: 'A1',
  white: 'A1', black: 'A1', red: 'A1', blue: 'A1', green: 'A1', say: 'A1',

  // A2 words
  argue: 'A2', culture: 'A2', basic: 'A2', double: 'A2', event: 'A2', period: 'A2',
  support: 'A2', increase: 'A2', result: 'A2', action: 'A2', example: 'A2', problem: 'A2',
  area: 'A2', case: 'A2', week: 'A2', company: 'A2', system: 'A2', program: 'A2',
  question: 'A2', government: 'A2', number: 'A2', story: 'A2', fact: 'A2', month: 'A2',
  business: 'A2', issue: 'A2', side: 'A2', kind: 'A2', service: 'A2', friend: 'A2',
  father: 'A2', power: 'A2', hour: 'A2', game: 'A2', line: 'A2', end: 'A2', among: 'A2',
  group: 'A2', lead: 'A2', turn: 'A2', mother: 'A2', money: 'A2', body: 'A2',
  music: 'A2', family: 'A2', help: 'A2', children: 'A2',
  country: 'A2', plant: 'A2', animal: 'A2', point: 'A2',
  word: 'A2', study: 'A2', still: 'A2', need: 'A2', large: 'A2', often: 'A2',
  follow: 'A2', important: 'A2', around: 'A2', another: 'A2', came: 'A2',
  could: 'A2', different: 'A2', during: 'A2', each: 'A2', earth: 'A2', enough: 'A2',
  every: 'A2', form: 'A2', found: 'A2', great: 'A2', hard: 'A2', heat: 'A2',
  idea: 'A2', land: 'A2', light: 'A2', miss: 'A2', near: 'A2', next: 'A2', once: 'A2',
  paper: 'A2', part: 'A2', plan: 'A2', real: 'A2', road: 'A2', same: 'A2',
  second: 'A2', start: 'A2',
  together: 'A2', town: 'A2', tree: 'A2', under: 'A2', until: 'A2', watch: 'A2',

  // B1 words
  negotiate: 'B1', conflict: 'B1', reveal: 'B1', aspect: 'B1', involve: 'B1', assess: 'B1',
  feature: 'B1', impact: 'B1', achieve: 'B1', approach: 'B1', benefit: 'B1', challenge: 'B1',
  communicate: 'B1', complex: 'B1', concept: 'B1', context: 'B1', contribute: 'B1',
  debate: 'B1', define: 'B1', demonstrate: 'B1', determine: 'B1', develop: 'B1',
  discuss: 'B1', distribute: 'B1', establish: 'B1', evaluate: 'B1', examine: 'B1',
  expand: 'B1', explain: 'B1', explore: 'B1', focus: 'B1', generate: 'B1', identify: 'B1',
  implement: 'B1', indicate: 'B1', interpret: 'B1', investigate: 'B1', maintain: 'B1',
  manage: 'B1', obtain: 'B1', occur: 'B1', participate: 'B1', perform: 'B1', present: 'B1',
  process: 'B1', produce: 'B1', promote: 'B1', provide: 'B1', publish: 'B1', reduce: 'B1',
  reflect: 'B1', relate: 'B1', require: 'B1', research: 'B1', respond: 'B1', review: 'B1',
  select: 'B1', significant: 'B1', source: 'B1', structure: 'B1', suggest: 'B1',
  summarize: 'B1', theory: 'B1', transfer: 'B1', transform: 'B1', modify: 'B1',
  motivate: 'B1', organize: 'B1', overcome: 'B1', prevent: 'B1', principle: 'B1',
  propose: 'B1', protect: 'B1', pursue: 'B1', acquire: 'B1', adapt: 'B1',
  affect: 'B1', assume: 'B1', aware: 'B1', capture: 'B1', classify: 'B1', compare: 'B1',

  // B2 words
  ambiguous: 'B2', perceive: 'B2', encounter: 'B2', acknowledge: 'B2', accumulate: 'B2',
  adequate: 'B2', advocate: 'B2', allocate: 'B2', analyze: 'B2', anticipate: 'B2',
  assert: 'B2', attribute: 'B2', circumstance: 'B2', collaborate: 'B2', compensate: 'B2',
  complement: 'B2', comprise: 'B2', concentrate: 'B2', constitute: 'B2', construct: 'B2',
  contrast: 'B2', controversial: 'B2', deduce: 'B2', diminish: 'B2', discriminate: 'B2',
  diverse: 'B2', elaborate: 'B2', eliminate: 'B2', emphasize: 'B2', enhance: 'B2',
  ensure: 'B2', equivalent: 'B2', estimate: 'B2', facilitate: 'B2', fluctuate: 'B2',
  formulate: 'B2', furthermore: 'B2', hypothesis: 'B2', illustrate: 'B2', immense: 'B2',
  implicit: 'B2', inappropriate: 'B2', inevitable: 'B2', infrastructure: 'B2',
  innovative: 'B2', integrate: 'B2', justify: 'B2', likewise: 'B2', manipulate: 'B2',
  mechanism: 'B2', minimize: 'B2', objective: 'B2', phenomenon: 'B2', preliminary: 'B2',
  prospect: 'B2', subsequent: 'B2', sufficient: 'B2', sustain: 'B2', undermine: 'B2',
  validity: 'B2', virtually: 'B2', widespread: 'B2', abstract: 'B2', coherent: 'B2',
  concrete: 'B2', fundamental: 'B2', ideological: 'B2', impose: 'B2',

  // C1 words
  eloquent: 'C1', scrutinize: 'C1', articulate: 'C1', paradox: 'C1', ambivalent: 'C1',
  apprehensive: 'C1', arbitrary: 'C1', archaic: 'C1', astute: 'C1', auspicious: 'C1',
  benevolent: 'C1', candid: 'C1', circumspect: 'C1', complacent: 'C1', convoluted: 'C1',
  cynical: 'C1', delineate: 'C1', depict: 'C1', despondent: 'C1', didactic: 'C1',
  diligent: 'C1', discern: 'C1', disparity: 'C1', dogmatic: 'C1', eccentric: 'C1',
  elusive: 'C1', eminent: 'C1', empirical: 'C1', eradicate: 'C1', erroneous: 'C1',
  exacerbate: 'C1', exemplary: 'C1', exhaustive: 'C1', explicit: 'C1', feasible: 'C1',
  formidable: 'C1', frivolous: 'C1', grandiose: 'C1', gregarious: 'C1', hypothetical: 'C1',
  impede: 'C1', incisive: 'C1', indifferent: 'C1', indulge: 'C1', inherent: 'C1',
  juxtapose: 'C1', lament: 'C1', lucid: 'C1', meticulous: 'C1', negligent: 'C1',
  nuanced: 'C1', obscure: 'C1', ostensible: 'C1', pervasive: 'C1', pragmatic: 'C1',
  profound: 'C1', prolific: 'C1', reconcile: 'C1', rhetoric: 'C1', sporadic: 'C1',
  tenacious: 'C1', ubiquitous: 'C1', vehement: 'C1',

  // C2 words
  ephemeral: 'C2', laconic: 'C2', obstinate: 'C2', abstruse: 'C2', perspicacious: 'C2',
  acrimonious: 'C2', alacrity: 'C2', anachronism: 'C2', arcane: 'C2', assuage: 'C2',
  audacious: 'C2', bellicose: 'C2', byzantine: 'C2', capricious: 'C2', chicanery: 'C2',
  circumlocution: 'C2', clandestine: 'C2', coalesce: 'C2', cogent: 'C2', conundrum: 'C2',
  cupidity: 'C2', dearth: 'C2', deference: 'C2', deleterious: 'C2', diaphanous: 'C2',
  dilettante: 'C2', dissemble: 'C2', ebullient: 'C2', effusive: 'C2', egregious: 'C2',
  enervate: 'C2', equivocate: 'C2', esoteric: 'C2', eulogy: 'C2', evanescent: 'C2',
  fastidious: 'C2', felicitous: 'C2', fractious: 'C2', garrulous: 'C2', hegemony: 'C2',
  hubris: 'C2', ignominious: 'C2', imperious: 'C2', impetuous: 'C2', inchoate: 'C2',
  inimical: 'C2', insidious: 'C2', intransigent: 'C2', loquacious: 'C2', mendacious: 'C2',
};

export const STOP_WORDS = new Set([
  'the', 'a', 'an', 'is', 'are', 'was', 'were', 'i', 'you', 'he', 'she', 'it', 'we',
  'they', 'and', 'or', 'but', 'in', 'on', 'at', 'to', 'for', 'of', 'with', 'this',
  'that', 'have', 'has', 'do', 'did', 'will', 'would', 'could', 'should', 'may', 'might',
  'shall', 'can', 'been', 'be', 'had', 'not', 'no', 'yes', 'so', 'if', 'as', 'by',
  'from', 'up', 'about', 'into', 'through', 'during', 'before', 'after', 'above',
  'below', 'between', 'out', 'off', 'over', 'under', 'then', 'than', 'too', 'very',
  'just', 'also', 'more', 'most', 'some', 'any', 'all', 'both', 'each', 'few', 'many',
  'much', 'other', 'such', 'own', 'same', 'its', 'their', 'our', 'your', 'my', 'his',
  'her', 'which', 'who', 'what', 'when', 'where', 'why', 'how', 'there', 'here', 'now',
  'only', 'still', 'yet', 'already', 'again', 'once', 'every', 'because', 'them', 'him',
  'these', 'those', 'me', 'us', 'got', 'get', 'let', 'go', 'come', 'oh', 'hey', 'ok',
  'okay', 'yeah', 'well', 'like', 'know', 'think', 'going', 'want', 'need', 'see', 'say',
  'said', 'told', 'tell', 'got', 'gonna', 'gotta', 'wanna',
]);
